chat/urls.py
from django.urls import path
from . import views


app_name = 'chat'
urlpatterns = [
    path('room/<int:course_id>/',
         views.course_chat_room, name='course_chat_room')
]

educa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from courses.views import CourseListView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('chat/', include('chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('register/',
         views.StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll_course/',
         views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(), name='student_course_list'),
    path('courses/<pk>/', cache_page(60 * 15)
         (views.StudentCourseDetailView.as_view()), name='student_course_detail'),
    path('courses/<pk>/<module_id>/', cache_page(60 * 15)
         (views.StudentCourseDetailView.as_view()), name='student_course_detail_module'),
]

students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                    widget=forms.HiddenInput)

students/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CourseEnrollForm
from django.views.generic.list import ListView
from courses.models import Course
from django.views.generic.detail import DetailView


class StudentRegistrationView(CreateView):
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'],
                            password=cd['password1'])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin,
                              FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('student_course_detail',
                            args=[self.course.id])


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/course/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(DetailView):
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get course object
        course = self.get_object()
        if 'module_id' in self.kwargs:
            # get current module
            context['module'] = course.modules.get(
                id=self.kwargs['module_id']
            )
        else:
            # get first module
            context['module'] = course.modules.all()[0]
        return context

students/templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <h1>{{ module.title }}</h1>
    <div class="contents">
        <h3>Modules</h3>
        <ul id="modules">
            {% for m in object.modules.all %}
                <li data-id="{{ m.id }}" {% if m == module %} class="selected"{% endif %}>
                    <a href="{% url 'student_course_detail_module' object.id m.id %}">
                        <span>
                            Module <span class="order">{{ m.order|add:1 }}</span>
                        </span>
                        <br>
                        {{ m.title }}
                    </a>
                </li>
            {% empty %}
                <li>No modules yet.</li>
            {% endfor %}
        </ul>
        <h3>
            <a href="{% url 'chat:course_chat_room' object.id %}"> Course chat room</a>
        </h3>
    </div>
    <div>
        {% cache 600 module_contents module %}
            {% for content in module.contents.all %}
                {% with item=content.item %}
                    <h2>{{ item.title }}</h2>
                    {{ item.render }}
                {% endwith %}
            {% endfor %}
        {% endcache %}
    </div>
{% endblock %}

students/templates/students/course/list.html
{% extends "base.html" %}
{% block title %}My courses{% endblock %}
{% block content %}
    <h1>My courses</h1>
    <div class="module">
        {% for course in object_list %}
            <div class="course-info">
                <h3>{{ course.title }}</h3>
                <p><a href="{% url 'student_course_detail' course.id %}">
                    Access contents
                </a></p>
            </div>
        {% empty %}
            <p>You are enrolled in any course yet.
            <a href="{% url 'course_list' %}">Browse courses</a>
                to enroll in a course.
            </p>
        {% endfor %}
    </div>
{% endblock %}